### ISSUE TITLE
Building site fail

### ISSUE THREAD

**Issue by GawenBerger** [realm/jazzy#305] opened 2015-09-22 15:53 UTC
I started to use jazzy today, and when I tried to build the documentation (using this command `jazzy --swift-version 2.0 -x -workspace,XXXX.xcworkspace,-scheme,XXXX`) I got a sourcekitten error.
My output is as followed :

```
Parsing XXXX.swift (X/X)
[...]
building site
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:233:in `make_source_declarations': undefined method `each' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:235:in `block in make_source_declarations'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:233:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:233:in `make_source_declarations'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:305:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:109:in `build_docs_for_sourcekitten_output'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:67:in `build'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/bin/jazzy:15:in `<top (required)>'
    from /usr/bin/jazzy:23:in `load'
    from /usr/bin/jazzy:23:in `<main>' 
```

I looked in sourcekitten.rb and it seemed that this line `docs.each do |doc|` fail because docs is nil.
This is the first time I use this kind of tools so maybe I did something wrong when installing or using it but I can't manage to make it work.
Does someone have any clue regarding why this is happening ?

Note : I tried a simple `jazzy --min-acl private` on a test project (no workspace) with really few code and it worked perfectly.

EDIT : I use Xcode7 with Swift 2.0

**Comment by jpsim** [comment] 2015-09-22 22:15
Is there any chance you could send us either the project itself, or another project that exhibits the same issue? That would help greatly in troubleshooting what's happening.

**Comment by GawenBerger** [comment] 2015-09-23 10:18
Ok, I spend a lot of time this morning trying to identify what made that happened and I finally identified it, I'm not sure if this is a bug or if this is simply a misusage, but what causes this is the presence of an empty swift file.
In my case, it was a full swift file commented but any swift file without functions/classes/enums/structs & co will make the build phase fail.

**Comment by p2** [comment] 2015-09-23 12:46
I have the same issue, trying to build documentation for the master branch of [the Swift-SMART](https://github.com/smart-on-fhir/Swift-SMART/) project.

**Comment by GawenBerger** [comment] 2015-09-23 14:44
I think it doesn't work for you because of [this file](https://github.com/smart-on-fhir/Swift-SMART/blob/master/Tests/BaseTests%2BiOS.swift). I tested this morning and an include in a file is not enough to avoid a crash, so I guess you could try to add something like "class ThisIsATest {}" in this file to see if this come from that.
I'm not sure if this will be enough because I got a lot of errors when I try to generate a documentation on your project :
```
[...]
Could not read contents of `/Users/.../Swift-FHIR/Models/DocumentManifest.swift`
Could not parse `DocumentManifest.swift`. Please open an issue at https://github.com/jpsim/SourceKitten/issues with the file contents.
[...]
```
But since there is this ```Parsing BaseTests+iOS.swift (6/162)```, I'm nearly sure from what I saw that this file is fully or in part responsible of your issue.

**Comment by p2** [comment] 2015-09-23 14:52
Whoa, I did see your comment and checked, but indeed this file is wrongly assigned to the main target, needs to be on the test target! I just removed it and indeed, that was it.

You got all these errors because of missing submodules, this framework must be cloned with `--recursive`, but you don't need to bother now. :)

Thanks a lot!

And to the maintainers, looks like Swift files that do not contain a class will crash jazzy. Thanks for a great product!

**Comment by jpsim** [comment] 2016-04-06 22:11
@GawenBerger did you ever make progress on this since the last activity on this issue? Is there anything we can do to help?

**Comment by GawenBerger** [comment] 2016-04-07 13:06
Hey @jpsim, since I figured out the way to "make it work" (aka taking care that jazzy doesn't run on any "empty" swift file) I didn't dig more into it.
If it's not urgent I have no problem trying to fix the bug but I would need some times as I never did Ruby before and I need at least basic knowledge of the language before being able to really look for the issue.

**Comment by istx25** [comment] 2016-11-23 15:15
Any progress on this? @GawenBerger

**Comment by jpsim** [comment] 2016-11-26 01:57
Yeah, basically need a repro case to move forward with this /cc @GawenBerger @p2.

**Comment by p2** [comment] 2016-11-26 07:31
I haven't had this issue since I removed the empty Swift file (empty save for an `import UIKit`, which was only there trying to circumvent an Xcode 7 unittest issue).

**Comment by GawenBerger** [comment] 2016-11-26 13:19
I told you everything you need to know earlier in this post, as p2 also said you just need any project with an empty swift file (or at least no func/class declaration, which mean an empty file with `import` still cause the crash).

**Comment by jpsim** [comment] 2016-11-26 17:11
Ah, this is likely a duplicate of the other issue(s) where we're tracking better handling of empty projects.

**Comment by johnfairh** [comment] 2019-02-04 10:36
Closing, empty files work fine now.

**Closed by johnfairh** 2019-02-04 10:36 UTC
Labels: bug, needs-investigation, needs-more-information
