### ISSUE TITLE
jazzy version: 0.7.0, can't get --exclude to ignore files

### ISSUE THREAD

**Issue by ort11** [realm/jazzy#619] opened 2016-07-22 21:11 UTC
Putting in the full file spec / path / name but jazzy is still include the file / class in the docs

Have tried /*, /filename.swift, etc.

Any help would be appreciated.

**Comment by garricn** [comment] 2016-08-12 22:44
Really enjoying our first time using jazzy, but this is also happening to us (me & @n4tr0n)

**Comment by seivan** [comment] 2016-08-15 14:58
Not just files, but also directories.
This is what we've tried with:
```yaml
exclude: ["SDK/Source/Vendored/", "SDK/Source/Vendored/*", "SDK/Source/Vendored/**/*", "SDK/Source/Vendored/*/**.swift"]
```

**Comment by radutzan** [comment] 2016-08-19 21:17
Same. Using the following statement on my .jazzy.yaml file:

    exclude:
      - Project/File.swift
      - Project/Directory/*

**Comment by seivan** [comment] 2016-08-30 10:13
Looks like https://github.com/realm/jazzy/pull/640 fix it

**Comment by aasatt** [comment] 2016-09-07 20:59
Still not able to get it to work. I am using the full path copied directly from the Project Navigator.

**Comment by p2** [comment] 2016-09-15 15:59
FYI, it didn't seem to work for me (which is why I found this), however the following works for me with jazzy 0.7.1 and a file `Sources/Keychain/Keychain.swift`:

    exclude: "**/Keychain.swift"

**Comment by istx25** [comment] 2016-11-23 22:50
Hi everyone! For some the problem has been resolved and for others it has not. This leads me to believe that there are either two (or more) problems or the original one wasn't actually fixed. Would someone (with more experience on this specific problem) be able to reproduce the problem on the latest version of Jazzy (and tools)? From there we can see what we need to do. :)

**Comment by grosch** [comment] 2017-01-09 04:22
Using version 0.7.3 I listed this in my .jazzy.yaml file:

source_directory: .
exclude: ./ExpandableDatePicker/Time\ Zone/Short/ShortTimeZoneDelegate.swift

And when I run jazzy, it still says parsing ShortTimeZoneDelegate.swift.  I've also tried without the path listed and just used the filename, but that made no difference.

**Comment by grosch** [comment] 2017-01-09 04:25
I also just tried what p2 did, using "**/*TimeZoneDelegate.swift" and that didn't work either.

**Comment by ekimia** [comment] 2017-01-16 01:25
same problem here trying to exclude a directory. Tried with the config file and the `exclude` flag

**Comment by grosch** [comment] 2017-01-16 18:37
I never got this to work, but I put the :nodoc: option in the public methods of the file I wanted excluded and that worked for me.

**Comment by wuf810** [comment] 2017-06-08 10:07
This doesn't work for me either. Is there every likely to be a fix?

**Comment by johnfairh** [comment] 2017-06-08 12:20
Can you post details of the problem?  jazzy version / project structure / jazzy config / jazzy invocation?

**Comment by wuf810** [comment] 2017-06-08 14:07
hey @johnfairh ignore me…I tried @p2 suggestion and it worked. From there I tried with different options using fullpath, relative paths and wildcards and they all work. So it's all ok.

Sorry for the noise!

**Comment by Minthos** [comment] 2017-06-26 16:12
I have this problem, but only with the file README.md

Looking at https://github.com/realm/jazzy/blob/master/lib/jazzy/readme_generator.rb I guess this may be a separate issue.

**Comment by johnfairh** [comment] 2017-06-27 14:15
@Minthos could you explain more about the problem that relates `--exclude` to README.md?

That ruby file is not used in the code right now.

**Comment by Minthos** [comment] 2017-06-27 15:25
I have a file in my project folder named README.md whose contents are automatically included in the generated docs/index.html

I have this in my .jazzy.yaml:
`exclude:
  - "**/README.md"`

I also tried with just
`exclude:
  - "README.md"`

and
`exclude:
  - README.md`

but it still got included. My current solution is to rename it to .README.md before running jazzy and renaming it back afterwards using a shell script.

**Comment by johnfairh** [comment] 2017-06-27 16:33
OK I see.  The `--exclude` option is meant for source code files, ie. .swift + .h's.

In case you hadn't seen it, the alternative to your workaround is to use `--readme` and give jazzy a markdown file (empty file works fine) that you do want to use for the index.html content.

**Comment by Minthos** [comment] 2017-06-27 17:15
Cool, thanks. I just tried with `--readme /dev/null` and it works. Updating my script :)

**Comment by drekka** [comment] 2017-07-27 07:15
In my case I'm trying to exclude a README.md file that is being picked up out of a third party source directory. i.e.. Not my code.

I'm running with `--documentation "**/*.md" --exclude "External"` because I have a number of Guides and other docs which I want to include and which are in various subdirectories. However I don't want to include `md` files from the `External` directory because that contains various 3rd party dependencies. 

I've tried all sorts of options in `--exclude` and so far nothing has worked. ie. `External/*`, `**/External`, `External/**/*.md`, blah, blah, blah.

I understand from comments above that `--exclude` is is filtering swift files which is why it's not working for me. 

Can I request that it be modified to filter ALL files queued for conversion to HTML.

Thanks

**Comment by johnfairh** [comment] 2017-07-27 08:38
The argument to `--documentation` is a [ruby glob](https://ruby-doc.org/core-2.2.0/Dir.html#method-c-glob).  This means you can write something like:\
`--documentation '{DocDir1,DocDir2}/**/*.md'`\
... to include specific directories rather than trying to exclude one -- might help here?

**Comment by drekka** [comment] 2017-07-31 07:32
Thanks @johnfairh but I don't think it will help. In my case the directory I want to exclude is a sub directory of the root directory of the project where the top level documentation is also kept. I guess the only thing I could do would be to move the documentation to another subdirectory and just include that. But I like having it in the root where it's 'in-my-face' :-)

**Comment by glennposadas** [comment] 2018-08-15 13:46
Hello guys, I need a quick help. I can't seem to exclude my ```AppDelegate.swift``` file. Whatever I do, it's still being parsed.

In my ```.jazzy.yaml``` file, I got:

```
exclude:
  - "**/AppDelegate.swft"
  - "BeepBeep/AppDelegate.swft"
```

and then I run 

> jazzy --min-acl internal --undocumented-text “No\need\for\documentation” --hide-documentation-coverage

Any ideas?

**Comment by glennposadas** [comment] 2018-08-15 13:47
Hello guys, I need a quick help. I can't seem to exclude my ```AppDelegate.swift``` file. Whatever I do, it's still being parsed.

In my ```.jazzy.yaml``` file, I got:

```
exclude:
  - "**/AppDelegate.swift"
  - "BeepBeep/AppDelegate.swift"
```

and then I run 

> jazzy --min-acl internal --undocumented-text “No\need\for\documentation” --hide-documentation-coverage

Any ideas?

**Comment by johnfairh** [comment] 2018-08-15 15:11
`--exclude` stops files from having their declarations put into the documentation, it doesn't stop files from appearing in the "Parsing FooBar.swift (X/Y)" list.  If you're still having problems then I recommend opening a new issue and describe the problem fully, including what version of things you are using.

**Comment by johnfairh** [comment] 2019-01-30 12:56
Closing - fixed.

**Closed by johnfairh** 2019-01-30 12:56 UTC
Labels: needs-investigation, needs-more-information

**Comment by manisha-PBH** [comment] 2021-01-01 12:15
I am getting a problem with command  `**jazzy --min-acl internal**`, It always gives me an error 
[xcodebuild-03E38A04-9BF5-476E-8D35-9FF4D5A45161.log](https://github.com/realm/jazzy/files/5758890/xcodebuild-03E38A04-9BF5-476E-8D35-9FF4D5A45161.log)

Whereas running in the terminal with this command `**jazzy --min-acl internal -x -workspace, ProjectName.xcworkspace,-scheme, ProjectName**` results in success. 

I have already imported IQKeyboardManager in the class. Also, it will be great if someone can provide me the command to exclude files in the terminal.

**Comment by johnfairh** [comment] 2021-01-04 11:25
@manisha-PBH This old issue contains examples of using `exclude` in the response file; the CLI version is `--exclude pathA,pathB,pathC`.  If that doesn't help then please open a new issue explaining what you are trying to do, what you have tried, and what's not working.
