### ISSUE TITLE
Problems with Jazzy when multiple versions of Xcode are installed

### ISSUE THREAD

**Issue by GuoZhiQiang** [realm/jazzy#593] opened 2016-06-13 10:29 UTC
ERROR:  Error installing jazzy:
    ERROR: Failed to build gem native extension.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
```

creating Makefile

make "DESTDIR="
make: **\* No rule to make target `"/Applications/Xcode', needed by`autolink.o'.  Stop.

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4/ext/redcarpet/gem_make.out

**Comment by segiddins** [comment] 2016-06-13 14:53
Do you have Xcode installed?

**Comment by GuoZhiQiang** [comment] 2016-06-14 02:17
I have installed two versions of Xcode: Xcode7.0，Xcode7.3

**Comment by jpsim** [comment] 2016-06-14 18:46
what happens with `[sudo] gem install redcarpet`?

**Comment by GuoZhiQiang** [comment] 2016-06-15 01:26
@jpsim have the same error

**Comment by GuoZhiQiang** [comment] 2016-06-15 03:12
@segiddins @jpsim I suggest you install two versions of Xcode, then install jazzy later

**Comment by jpsim** [comment] 2016-06-15 06:22
Installing two versions of Xcode really shouldn't be necessary.

**Comment by ewanmellor** [comment] 2016-06-23 01:20
@GuoZhiQiang Do you have a space in your Xcode directory?  Is it something like "/Applications/Xcode 7.0"?  If so, try removing the space.  My guess is that `No rule to make target "/Applications/Xcode'` is indicating that the path has been chopped at the space.

**Comment by GuoZhiQiang** [comment] 2016-07-06 10:50
As I said above，I have installed two versions of Xcode. When I remove One of the Xcodes, jazzy installed successed.

**Comment by GuoZhiQiang** [comment] 2016-07-06 11:13
I suppose because of I have installed two versions of Xcode, One name of the Xcodes is `Xcode`, Another name is `Xcode2`(the high version's name). That lead to *jazzy* cannot adapt itself( it may be puzzled on  which one to depend)

**Comment by jpsim** [comment] 2016-07-06 12:53
> I suppose because of I have installed two versions of Xcode, One name of the Xcodes is Xcode, Another name is Xcode2(the higher version's name). That lead to jazzy cannot adapt itself( it may be puzzled on which one to depend)

This shouldn't happen.

**Comment by GuoZhiQiang** [comment] 2016-07-08 08:08
But it happened. I don't know why

**Comment by jpsim** [comment] 2016-07-08 14:01
It seems more likely that one of the versions of Xcode you previously had installed isn't compatible with the version of ruby or redcarpet you were installing.

**Comment by GuoZhiQiang** [comment] 2016-07-09 03:24
My system is OS X 10.11.2, the ruby's version is 2.0.0（2015-04-13 revison 50299）. And the versions of Xcode I previously had installed are Xcode7.0 and Xcode7.3. But I can hardly to know this may effect the jazzy

**Comment by agentk** [comment] 2016-07-12 12:53
Hey @GuoZhiQiang.
Have you tried updating ruby? Ie, `brew install ruby`
Jazzy from stock install activesupport which requires ruby 2.2.2.
I've just installed it successfully from a clean system after installing brew and ruby (2.3.1).

**Comment by segiddins** [comment] 2016-07-14 03:22
@agentk you can just `gem install activesupport -v '< 5'`

**Comment by agentk** [comment] 2016-07-14 03:24
Oh. That tip will come in handy thanks @segiddins !!

**Comment by GuoZhiQiang** [comment] 2016-07-14 09:46
Thanks all of you, as I have said above, i just had Xcode7.0 removed. Then Jazzy was installed successed（I have not  updated ruby）. Do you mean that I can just have ruby updated（ if I don't remove the Xcode） and Jazzy will be installed successed? @agentk

**Comment by agentk** [comment] 2016-07-14 10:18
It's an odd error that I'm not able to replicate. So this is a bit of stabbing in the dark. The tip from @segiddins is spot on for installing jazzy with the stock ruby. I wonder if it's to do with the selected Xcode?

To check which of the versions is selected use:
```
xcode-select --print-path
# Example output:
# /Applications/Xcode.app/Contents/Developer
```
And double check with
```
xcodebuild -version
# Example output:
# Xcode 7.3.1
# Build version 7D1014
```

I'm wondering if the latest Xcode needs to be selected for you to install jazzy. You can switch the selected Xcode with: (replacing Xcode2 with your other Xcode)
```
sudo xcode-select --switch /Applications/Xcode2.app/Contents/Developer
```
Then try installing jazzy again:
```
gem install activesupport -v '< 5'
gem install jazzy
```

**Comment by istx25** [comment] 2016-11-23 22:18
I'll look into trying to reproduce this more in the coming weeks.

**Comment by erhnby** [comment] 2018-06-22 09:20
I have faced same issue and solved it by selecting Xcode version which is just contains 'Xcode' as  name , not 'XCode X.Y'
strange

**Comment by uliwitness** [comment] 2018-11-08 16:28
Having the same issue:

	UliBoxBook:~ uli$ sudo gem install activesupport -v '< 5'
	Successfully installed activesupport-4.2.10
	Parsing documentation for activesupport-4.2.10
	Done installing documentation for activesupport after 2 seconds
	1 gem installed
	UliBoxBook:~ uli$ sudo gem install jazzy
	Building native extensions.  This could take a while...
	ERROR:  Error installing jazzy:
		ERROR: Failed to build gem native extension.

		current directory: /Library/Ruby/Gems/2.3.0/gems/redcarpet-3.4.0/ext/redcarpet
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20181108-42438-jjkw33.rb extconf.rb
	creating Makefile

	current directory: /Library/Ruby/Gems/2.3.0/gems/redcarpet-3.4.0/ext/redcarpet
	make "DESTDIR=" clean

	current directory: /Library/Ruby/Gems/2.3.0/gems/redcarpet-3.4.0/ext/redcarpet
	make "DESTDIR="
	make: *** No rule to make target `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h', needed by `autolink.o'.  Stop.

	make failed, exit code 2

	Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/redcarpet-3.4.0 for inspection.
	Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/redcarpet-3.4.0/gem_make.out
	UliBoxBook:~ uli$ sudo xcode-select --print-path
	/Applications/Xcode.app/Contents/Developer
	UliBoxBook:~ uli$ xcodebuild -version
	Xcode 10.1
	Build version 10B61

Any ideas on how to fix it? This is on 10.14.1 "Mojave".

**Comment by uliwitness** [comment] 2018-11-14 14:31
Nevermind, while that makes Redcarpet build and gets me a Jazzy executable, that then fails:

    building site
    bundler: failed to load command: jazzy (/usr/local/lib/ruby/gems/2.5.0/bin/jazzy)
    Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/uli/Programming/objectbox-swift/ios-framework/docs/jazzy_theme/templates/doc.mustache
  /usr/local/lib/ruby/gems/2.5.0/gems/mustache-0.99.8/lib/mustache/settings.rb:142:in `read'

So seems mustache has an issue?

**Comment by uliwitness** [comment] 2018-11-19 11:21
I tried on another boot disk to use a JVM Ruby instead, and that runs through. After using that on its own partition (but with the same checkout), I can now also build on the original install with the Homebrew Ruby. Which is weird, but maybe the Mustache thing only has to run through once and gets cached?

**Comment by jnross** [comment] 2018-11-29 18:12
I see the same issue on Mojave 10.14.1, just as @uliwitness reported.  This is a new machine, it has only ever had Xcode 10.1 installed.  

```
make: *** No rule to make target `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h', needed by `autolink.o'.  Stop.
```

Looking in `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/`, I see that there is no `universal-darwin18` directory, only `universal-darwin17`.  Does anyone know why it would be looking for for `universal-darwin18` and unable to use `universal-darwin17` ?

I will also report this to the `redcarpet` maintainers, since this also happens when I run `gem install redcarpet`.

**Comment by uliwitness** [comment] 2018-11-29 21:59
Feel free to let us know the issue number so we can all pile on :-)

**Comment by jnross** [comment] 2018-12-03 21:30
Sorry for the delay, but here is the issue I created:  https://github.com/vmg/redcarpet/issues/668.  We'll see what happens.

**Comment by johnfairh** [comment] 2019-01-04 10:49
OP was suffering from the 'space in Xcode path' problem, clear from the error message, written up in #994.

The issue later down the thread is different:
> `make: *** No rule to make target /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h', needed by 'autolink.o'.  Stop.`

This is a system setup problem: with macOS stock Ruby, the header files are inside Xcode's macOS SDK not `/System`.  There should not even be a `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include` directory -- if you somehow have one though, then Ruby will get confused and look for header files there instead of inside Xcode.

A useful command to run is `ruby -rrbconfig -e 'puts RbConfig::CONFIG["includedir"]'` -- if you are using stock Ruby [ie. not using rvm/rbenv] this should point inside Xcode.

It looks like you might get this same error if you don't install/upgrade the CLI developer tools as well: could be at least one of the users seeing the error is due to this.

But @jnross above says they actually have the `/System/.../include` directory, mysterious!  Any clues from creation time etc. about where this dir came from?  For comparison my laptop came with macOS 10.13.something, no system restore, and has been upgraded to 10.14.2. (+ does not have the poison dir...)

**Comment by johnfairh** [comment] 2019-01-12 17:03
@adtrevor first check one more time that the Xcode CLI tools are working, `swift --version` gives good output.

If that doesn't help then probably the easiest way to install jazzy is going to be getting a different Ruby installation via homebrew and use that, rather than the system one that seems to be broken.  What exact OS are you on?  My Mac on 10.14.2 does not have the probably-bad `/System/...include` directory but jnross above who definitely does have it was on 10.14.1.

**Comment by adtrevor** [comment] 2019-01-12 17:06
Swift is available and working (Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Target: x86_64-apple-darwin18.0.0).

I did install Ruby via Homebrew too.

**Comment by johnfairh** [comment] 2019-01-14 17:39
macOS 10.14.2 is darwin18.2.0.  From the output above (darwin18.0.0) the system is pre-10.14.2.  So new theory: this is an OS problem introduced in 10.14.0 or 10.14.1 and fixed in 10.14.2.

**Comment by adtrevor** [comment] 2019-01-14 18:31
@johnfairh Will update and report if it solved the issue! Thank you

**Comment by johnfairh** [comment] 2019-01-14 19:41
@jnross 'missing' isn't quite right, it's not supposed to be there -- do you mean that you still have the `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include` directory?

**Comment by jnross** [comment] 2019-01-14 21:45
It's missing in the sense that the redcarpet (and other ruby) build process is looking for a header in that directory, and fails because it is not there.  

`/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin17` does exist, and appears to contain the desired header. 

 I tried to work around this by duping `universal-darwin17` to `universal-darwin18`, but was prevented by SIP.  I haven't tried disabling SIP for this workaround.

**Comment by adtrevor** [comment] 2019-01-14 22:55
Didn't do anything for me either

**Comment by yacir** [comment] 2019-02-13 16:23
Here is the solution that works for me https://github.com/jekyll/jekyll/issues/7274#issuecomment-425069689

**Comment by classified** [comment] 2019-04-29 10:29
Getting same error while installing jazzy on macOS 10.14.4. 

```
Building native extensions.  This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

	current directory: /Library/Ruby/Gems/2.3.0/gems/redcarpet-3.4.0/ext/redcarpet
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20181108-42438-jjkw33.rb extconf.rb
creating Makefile

current directory: /Library/Ruby/Gems/2.3.0/gems/redcarpet-3.4.0/ext/redcarpet
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.3.0/gems/redcarpet-3.4.0/ext/redcarpet
make "DESTDIR="
make: *** No rule to make target `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h', needed by `autolink.o'.  Stop.

make failed, exit code 2
```

**Comment by johnfairh** [comment] 2019-04-29 11:32
@classifed the output above has references to '/Library' so it is not using the brew-installed ruby.

**Comment by classified** [comment] 2019-04-29 11:46
@johnfairh Please check the second output with the brew installation.

```
Building native extensions. This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.6.0/gems/redcarpet-3.4.0/ext/redcarpet
/usr/local/opt/ruby/bin/ruby -I /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0 -r ./siteconf20190429-36055-1lpta4g.rb extconf.rb
creating Makefile

current directory: /usr/local/lib/ruby/gems/2.6.0/gems/redcarpet-3.4.0/ext/redcarpet
make "DESTDIR=" clean

current directory: /usr/local/lib/ruby/gems/2.6.0/gems/redcarpet-3.4.0/ext/redcarpet
make "DESTDIR="
compiling autolink.c
dyld: Library not loaded: /usr/local/lib/libwep
  Referenced from: /usr/bin/clang
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libwep: code signature in (/usr/local/lib/libwep) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/lib/libwep: stat() failed with errno=1
make: *** [autolink.o] Abort trap: 6

make failed, exit code 2

Gem files will remain installed in /usr/local/lib/ruby/gems/2.6.0/gems/redcarpet-3.4.0 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-18/2.6.0/redcarpet-3.4.0/gem_make.out
```

**Comment by johnfairh** [comment] 2019-04-29 12:23
You look to have already opened vmg/redcarpet#675 for this.  Probably want to - at least temporarily - uninstall whatever has installed that dodgy `libwep`.

**Comment by classified** [comment] 2019-04-29 13:41
> You look to have already opened [vmg/redcarpet#675](https://github.com/vmg/redcarpet/issues/675) for this. Probably want to - at least temporarily - uninstall whatever has installed that dodgy `libwep`.

I was Finally able to install Jazzy on macOS Mojave. it might be able to help you guys.

Steps:
1. Install latest `ruby` via `homebrew`
2. Make it `default` via Omitting `PATH`
3. Reboot to recovery mode and DISABLE SIP via `csrutil disable`
4. Open `Terminal` and install jazzy via `sudo gem install jazzy`
5. Reboot and Enable SIP again via `csrutil enable`
6. Now type Jazzy if command is not found then install it via this command again `sudo gem install -n /usr/local/bin jazzy`
7. Voila Jazzy is installed on macOS Mojave.

P.S. Used system had macOS Mojave 10.14.4 and Ruby 2.6.3

Thanks & Cheers

**Comment by ChrisMarshallNY** [comment] 2019-09-16 10:19
Just FYI. I had this problem after I made the "full switch" to Xcode 11.

From the above comments, I figured out what the issue was. Here's how I fixed it:

1) I signed into my Apple Developer account.
2) I went to the Downloads page, and then selected "More" (upper right corner).
3) I downloaded Xcode 10.3. I expanded it, and named it "Xcode10.3.app", and placed it in /Applications.
4) I ran this command line: `sudo xcode-select --switch /Applications/Xcode10.3.app/Contents/Developer`
5) I then ran `sudo gem install jazzy`.

Installation ran well.

However, you need to keep the path to RUN Jazzy. In fact, it won't run properly unless you retrofit your Xcode tools (You can also get the installer from Developer Downloads).

Once it is all done, you can run `sudo xcode-select --reset` or `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer` to restore the Xcode paths.

**Comment by johnfairh** [comment] 2019-09-16 15:08
It sounds like your system is not Catalina and so has the problem where the Xcode Ruby dev package does not match the /System Ruby package.  That is not this issue, and will hopefully go away in macOS 2020 when they stop shipping Ruby.

**Comment by ChrisMarshallNY** [comment] 2019-09-16 18:18
Cool. That makes sense. Thanks for the clarification!

**Comment by johnfairh** [comment] 2019-11-25 11:44
Closing now, the remaining issue to do with a mysterious directory under `/System` -- looks to have been somehow related to macOS 2018, nobody has seen it this year.

**Closed by johnfairh** 2019-11-25 11:44 UTC
Labels: bug, needs-investigation, needs-more-information

**Comment by jbarros35** [comment] 2020-05-21 08:18
> > You look to have already opened [vmg/redcarpet#675](https://github.com/vmg/redcarpet/issues/675) for this. Probably want to - at least temporarily - uninstall whatever has installed that dodgy `libwep`.
> 
> I was finally able to install Jazzy on macOS Mojave. it might be able to help you guys.
> 
> Steps:
> 
> 1. Install latest `ruby` via `homebrew`
> 2. Make it `default` via Omitting `PATH`
> 3. Reboot to recovery mode and DISABLE SIP via `csrutil disable`
> 4. Open `Terminal` and install jazzy via `sudo gem install jazzy`
> 5. Reboot and Enable SIP again via `csrutil enable`
> 6. Now type Jazzy if command is not found then install it via this command again `sudo gem install -n /usr/local/bin jazzy`
> 7. Voila Jazzy is installed on macOS Mojave.
> 
> P.S. Used system had macOS Mojave 10.14.4 and Ruby 2.6.3
> 
> Thanks & Cheers

It does not work for Mojave. The recover terminal can't access any gem or install.
I can't understand how do you do that.

**Comment by deepesh-vasthimal-cko** [comment] 2021-01-18 06:36
I have same issue not working below are my logs, Please can anyone suggest. I did install latest version of ruby but seems like below jazzy install command is still using the older version of ruby not sure if that is the issue ? Any help. 

 sudo gem install jazzy                               
Password:
Building native extensions. This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.1/ext/redcarpet
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20210115-61907-31fr65.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.1 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/redcarpet-3.5.1/gem_make.out
deepesh.vasthimal@CKO-4256 bin % sudo gem install jazzy
Building native extensions. This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.1/ext/redcarpet
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20210118-74096-1s211ok.rb extconf.rb
creating Makefile

current directory: /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.1/ext/redcarpet
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.1/ext/redcarpet
make "DESTDIR="
make: *** No rule to make target `/Users/deepesh.vasthimal/Documents/Xcodes/Xcode_12.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19/ruby/config.h', needed by `autolink.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.1 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/redcarpet-3.5.1/gem_make.out
deepesh.vasthimal@CKO-4256 bin % xcode-select -p
/Users/deepesh.vasthimal/Documents/Xcodes/Xcode_12.3.app/Contents/Developer

**Comment by deepesh-vasthimal-cko** [comment] 2021-01-18 06:50
This is what worked for me 

deepesh.vasthimal@CKO-4256 bin % ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
deepesh.vasthimal@CKO-4256 bin % echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile
deepesh.vasthimal@CKO-4256 bin % source ~/.bash_profile
deepesh.vasthimal@CKO-4256 bin % ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]

After updating the ruby did a `sudo gem install jazzy ` and worked.
