### ISSUE TITLE
Can't Run swift-2.0 Build from Xcode "Run Scripts" Phase

### ISSUE THREAD

**Issue by nicolas-miari** [realm/jazzy#288] opened 2015-09-03 01:25 UTC
I got the `swift-2.0` branch working from the command line, but when I attempt to run the same command from my Xcode target's "Run Script" build phase, I get this error output:

    /Users/(my_username)/Projects/Jazzy/jazzy.gemspec:17: warning: Insecure world writable dir /usr in PATH, mode 040777
    /Users/(my_username)/Projects/Jazzy/lib/jazzy/sourcekitten.rb:72:in `run_sourcekitten': undefined method     `as_env' for nil:NilClass (NoMethodError)
        from /Users/(my_username)/Projects/Jazzy/lib/jazzy/doc_builder.rb:53:in `block in build'
        from /Users/(my_username)/Projects/Jazzy/lib/jazzy/doc_builder.rb:51:in `chdir'
        from /Users/(my_username)/Projects/Jazzy/lib/jazzy/doc_builder.rb:51:in `build'
        from /Users/(my_username)/Projects/Jazzy/bin/jazzy:15:in `<main>'
    Command /bin/sh failed with exit code 1

I am using Xcode 7 beta 6, and `xcode-select --print-path` on Terminal yields:

    /Applications/Xcode-Beta.app/Contents/Developer

**Comment by segiddins** [comment] 2015-09-03 01:28
Did you pass the `--swift-version 2.0` option to `jazzy` ?

**Comment by nicolas-miari** [comment] 2015-09-03 01:52
Oh, I didn't know that option (nor did I think it woukld be necessary... I'm using a version of jazzy built from the `swift-2.0` branch after all).

Also, from the command line it is working without the switch.

If I add that switch, the build finishes without errors but it takes forever (Xcode progress bar gets stuck at about 80%): several minutes for a project that should build in one or two seconds.

**Comment by mbogh** [comment] 2015-09-15 15:05
Getting the same error, can't even `rake spec` without a lot of errors like

```
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `Moya` from `ROOT/tmp/document_moya_podspec`
Downloading dependencies
Installing Alamofire (1.2.3)
Installing LlamaKit (0.6.0)
Installing Moya (0.6.1)
Installing ReactiveCocoa (3.0-alpha.3)
Generating Pods project
ROOT/lib/jazzy/sourcekitten.rb:126:in `run_sourcekitten': undefined method `as_env' for nil:NilClass (NoMethodError)
	from ROOT/lib/jazzy/podspec_documenter.rb:18:in `block (2 levels) in sourcekitten_output'
	from ROOT/lib/jazzy/podspec_documenter.rb:17:in `map'
	from ROOT/lib/jazzy/podspec_documenter.rb:17:in `block in sourcekitten_output'
	from ROOT/lib/jazzy/podspec_documenter.rb:16:in `chdir'
	from ROOT/lib/jazzy/podspec_documenter.rb:16:in `sourcekitten_output'
	from ROOT/lib/jazzy/doc_builder.rb:52:in `build'
	from ROOT/bin/jazzy:15:in `<main>'

	spec/integration_spec.rb:132:in `block (3 levels) in <top (required)>'
	spec/integration_spec.rb:131:in `block (2 levels) in <top (required)>'
	spec/integration_spec.rb:92:in `block in <top (required)>'
	spec/integration_spec.rb:77:in `<top (required)>'
	/Users/.../.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
	/Users/.../.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ivanicspeter92** [comment] 2015-09-17 10:31
Same problem here, I am trying to run jazzy from my project's folder, then the following error appears: 
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:116:in `run_sourcekitten': undefined method `as_env' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:56:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:54:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:54:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'

Sourcekitten is installed. Am I missing something or do I do something wrong here?

**Comment by mattgabor** [comment] 2015-10-29 00:33
Hey all, any solution to this issue? I am running Xcode 7.1 and when I Jazzy through gem. When I type jazzy in my project's directory I get the following error:

/Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/sourcekitten.rb:125:in `run_sourcekitten': Unable to find an Xcode with swift version 2.0. (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/doc_builder.rb:56:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/doc_builder.rb:54:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/doc_builder.rb:54:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

**Comment by jpsim** [comment] 2015-10-29 00:36
@mattgabor as the error message indicates, jazzy was `Unable to find an Xcode with swift version 2.0.`. Since you've said you have Xcode 7.1 installed, you'll have to pass in `--swift-version 2.1` for jazzy to use Xcode 7.1.

**Comment by jpsim** [comment] 2015-10-29 00:36
I'm closing this issue, but if anyone can provide steps for us to reproduce, I'll be happy to reopen.

**Closed by jpsim** 2015-10-29 00:36 UTC

**Comment by DaskiOFF** [comment] 2015-12-18 10:29
Hi, I have xcode version 7.2.
Called from the root project folder
`jazzy --objc --author DaskOFF --author_url https://github.com/DaskiOFF/ --github_url https://github.com/DaskiOFF/RKBaseClass --github-file-prefix https://github.com/DaskiOFF/RKBaseClass/tree/0.0.2 --module-version 0.0.2 --umbrella-header RKBaseClass/NSObject+RKBaseClass.h --framework-root . --module RKBaseClass --clean --swift-version 2.1`

And get the error
`/usr/local/lib/ruby/gems/2.1.0/gems/jazzy-0.4.1/lib/jazzy/sourcekitten.rb:137:in `run_sourcekitten': Unable to find an Xcode with swift version 2.1. (RuntimeError)
	from /usr/local/lib/ruby/gems/2.1.0/gems/jazzy-0.4.1/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jazzy-0.4.1/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jazzy-0.4.1/lib/jazzy/doc_builder.rb:55:in `build'
	from /usr/local/lib/ruby/gems/2.1.0/gems/jazzy-0.4.1/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'`

**Comment by segiddins** [comment] 2015-12-18 10:36
Xcode 7.2 has swift version 2.1.1

**Comment by DaskiOFF** [comment] 2015-12-18 11:26
@segiddins, thank you

**Comment by akhilcb** [comment] 2018-01-19 02:08
How do we integrate jazzy with Xcode build phase? Since Jazzy invokes xcodebuild, it looks like going in an infinite loop there. Could you please share steps to integrate with Xcode build phase without invoking xcodebuild when running jazzy? I think this is what @nicolas-miari has mentioned above too as the issue.
