### ISSUE TITLE
Cannot include filepaths with spaces.

### ISSUE THREAD

**Issue by StanRosenbaum98point6** [realm/jazzy#1295] opened 2021-12-03 22:07 UTC
I have the following in a zsh script I am using in conjunction with Jazzy.

`	INCLUDED_FILES="--include=/SDK/Public interface/*"`

I then form the final command later on.

However I get the following error when I run the script later on.

`WARNING: Leftover unused command-line text: ["interface/*"]`

I have also tried the same with 

`	INCLUDED_FILES="--include=/SDK/Public\ interface/*"`

and get the same result.

Is this a bug, or is there a way to get Jazzy to recognize filepaths with spaces?

**Comment by johnfairh** [comment] 2021-12-04 09:47
This means the script is not quite getting the quoting/escaping right: the jazzy process is not being passed the parameters as intended.

You could try writing out the command long-form on the CLI to prove to yourself it works (or prove to us it doesn't!) and then slowly refactor into env variables.

Or use the config file instead of passing things on the CLI.

**Comment by johnfairh** [comment] 2021-12-20 17:26
Closing, answered.

**Closed by johnfairh** 2021-12-20 17:26 UTC
Labels: help
