### ISSUE TITLE
Cannot generate documentation for CocoaPod lib with Swift 3, Xcode 8

### ISSUE THREAD

**Issue by benrudhart** [realm/jazzy#659] opened 2016-09-14 14:40 UTC
I'm trying to generate documentation for a CocoaPod lib when using Swift 3.0, Xcode 8 and Jazzy 0.7.1.

I specified the podspec via `.jazzy.yaml`. When running `jazzy` it throws the following error:

```
[...]
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: ...log
[...]
```

I checked the generated log file and it states this:

```
[...]
The file “JazzyPodsXC8.xcconfig” couldn’t be opened because there is no such file. (<PathToRepo>/Example/Pods/Target Support Files/JazzyPodsXC8/JazzyPodsXC8.xcconfig)
error: unable to read module map contents from 'Target Support Files/JazzyPodsXC8/JazzyPodsXC8.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “JazzyPodsXC8.modulemap” couldn’t be opened because there is no such file." 
[...]
```

These files do exists - I don't know where Jazzy is looking for them.

I created an example project for this issue and pushed it here: https://github.com/benrudhart/JazzyPodsXc8

Any hints to what I'm doing wrong? Maybe this is related to my [.jazzy.yaml](https://github.com/benrudhart/JazzyPodsXc8/blob/master/.jazzy.yaml) configuration. But I'm pretty sure that this used to work with a previous beta of Xcode 8

**Comment by olddonkey** [comment] 2016-09-17 14:29
Same

**Comment by jweinst1** [comment] 2016-11-16 02:32
same

**Comment by istx25** [comment] 2016-11-23 23:22
I believe this is a duplicate of #657. Closing.

**Comment by jpsim** [comment] 2016-11-26 04:37
Seems entirely unrelated to #657. Reopening.

**Comment by garricn** [comment] 2016-11-27 21:06
I believe I'm having the same issue.

**Comment by WildDylan** [comment] 2016-11-28 03:29
#683 same issue

**Comment by jpsim** [comment] 2016-12-07 19:51
It'd be helpful when people post that they're having a problem, that they would share enough information for a jazzy contributor to look further into it. Such as steps to reproduce. It looks like there's a lot more info in #683 so I'll read up on that one.

**Comment by johnfairh** [comment] 2019-01-28 13:51
Closing, old - original example project works fine on latest everything.

**Closed by johnfairh** 2019-01-28 13:51 UTC
Labels: bug, needs-investigation
