### ISSUE TITLE
Unable to Generate DOCS for my Pod

### ISSUE THREAD

**Issue by prakashraman** [realm/jazzy#491] opened 2016-02-25 17:48 UTC
I have created a CocoaPod PineKit (https://github.com/1985apps/PineKit)

I am trying to generate the documentation using command "jazzy". I am running this at the root folder of my pod.

I get the following error
```
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/33/2d2byrh50m75ywrwgvlvfz500000gn/T/xcodebuild-1431F88A-12D3-41C4-83EA-24536B3484E6.log
Failed to generate documentation
/Users/prakashraman/.rvm/gems/ruby-2.2.3/gems/jazzy-0.5.0/lib/jazzy/executable.rb:36:in `execute_command': /Users/prakashraman/.rvm/gems/ruby-2.2.3/gems/jazzy-0.5.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--module-name", "PineKit"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/33/2d2byrh50m75ywrwgvlvfz500000gn/T/xcodebuild-1431F88A-12D3-41C4-83EA-24536B3484E6.log

Failed to generate documentation
	from /Users/prakashraman/.rvm/gems/ruby-2.2.3/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten'
	from /Users/prakashraman/.rvm/gems/ruby-2.2.3/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Users/prakashraman/.rvm/gems/ruby-2.2.3/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Users/prakashraman/.rvm/gems/ruby-2.2.3/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Users/prakashraman/.rvm/gems/ruby-2.2.3/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
	from /Users/prakashraman/.rvm/gems/ruby-2.2.3/bin/jazzy:23:in `load'
	from /Users/prakashraman/.rvm/gems/ruby-2.2.3/bin/jazzy:23:in `<main>'

````

Any thoughts ?

**Comment by jpsim** [comment] 2016-04-06 07:49
Seems to work fine for me:

```
$ git clone git@github.com:1985apps/PineKit.git
$ cd PineKit
$ jazzy --podspec PineKit.podspec
Updating local specs repositories

CocoaPods 1.0.0.beta.6 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Fetching podspec for `PineKit` from `/Users/jp/Projects/PineKit`
Downloading dependencies
Installing Cartography (0.6.0)
Installing PineKit (0.1.0)
Installing SnapKit (0.15.0)
Installing SwiftyJSON (2.3.2)
Generating Pods project
Pod installation complete! There is 1 dependency from the Podfile and 4 total pods installed.
Running xcodebuild
Parsing PineBarGraph.swift (1/33)
Parsing PineBarGraphHorizonalGridLine.swift (2/33)
Parsing PineBarGraphYSet.swift (3/33)
Parsing PineBaseMenuView.swift (4/33)
Parsing PineBaseViewController.swift (5/33)
Parsing PineButton.swift (6/33)
Parsing PineCardView.swift (7/33)
Parsing PineConfig.swift (8/33)
Parsing PineFluidGridLayout.swift (9/33)
Parsing PineIcon.swift (10/33)
Parsing PineImagePicker.swift (11/33)
Parsing PineJSONModel.swift (12/33)
Parsing PineLabel.swift (13/33)
Parsing PineLinearLayout.swift (14/33)
Parsing PineMenuDelegate.swift (15/33)
Parsing PineMenuTransition.swift (16/33)
Parsing PineMenuTransitionSlideOverContent.swift (17/33)
Parsing PineMenuTransitionSqueeze.swift (18/33)
Parsing PineMenuTransitionXY.swift (19/33)
Parsing PineMenuViewController.swift (20/33)
Parsing PineProfileImageView.swift (21/33)
Parsing PineRadioGroup.swift (22/33)
Parsing PineRadioGroupItem.swift (23/33)
Parsing PineRangeSlider.swift (24/33)
Parsing PineSegmentedControll.swift (25/33)
Parsing PineSelectGroup.swift (26/33)
Parsing PineSelectGroupItem.swift (27/33)
Parsing PineSelectTextFieldInputView.swift (28/33)
Parsing PineSimpleData.swift (29/33)
Parsing PineSwipeView.swift (30/33)
Parsing PineSwitch.swift (31/33)
Parsing PineTextField.swift (32/33)
Parsing ReplaceMe.swift (33/33)
building site
jam out ♪♫ to your fresh new docs in `docs`
```

Which generates the following: http://static.realm.io/jazzy_demo/PineKit/index.html

I'll close this issue because I can't reproduce the issues you've been having, but please reopen if you can share more information for me to troubleshoot your issue!

**Closed by jpsim** 2016-04-06 07:49 UTC
Labels: question

**Comment by dimpiax** [comment] 2017-01-08 12:24
```
jazzy --podspec PineKit.podspec                                                                                                                                                        mac@dimpiax
Analyzing dependencies
Fetching podspec for `PineKit` from `/Users/mac/Documents/Work/PineKit`
Downloading dependencies
Installing Alamofire (3.5.1)
Installing PineKit (2.3.0)
Installing SnapKit (3.1.2)
Installing SwiftyJSON (3.1.3)
Generating Pods project
Skipping User Project Integration
Pod installation complete! There is 1 dependency from the Podfile and 4 total pods installed.
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/x4/7pzd2f5921x9xj_sc251cxz80000gn/T/xcodebuild-4DE0E55E-3076-4D41-A6BC-6C7EC200B202.log
Failed to generate documentation
```

**Comment by raginmari** [comment] 2017-11-07 21:39
I had the same (?) issue with one of my cocoapods. I use Xcode 8.2.1 and Swift 3.0.2.

Looking at the `xcodebuild` log mentioned in the error message I noticed that `xcodebuild` would set its `SWIFT_VERSION` variable to "4.0" (which typically comes with Xcode 9.x and which is not installed on my machine).

The `jazzy` command can be called with the option "--swift-version 3.0.2" (you can check the active Swift version via "swift --version" in the terminal).

Adding this option to the `jazzy` call fixed the problem in my case.
