### ISSUE TITLE
Incorrect Extension Class Parsing

### ISSUE THREAD

**Issue by Baza207** [realm/jazzy#153] opened 2015-01-15 01:44 UTC
After documenting a few of my extension classes I noticed that they were always being parsed correctly. It seems to be mainly header for the class and from all my documented extensions I have had 3 different incorrect results.    

All extension classes have the same formatted header where `<Class>` is replaced by the class name of the extension.
``` Swift
///
/// Extention functions for <Class>
///
extension <Class> {
```

1. The extension class just shows as undocumented.
![screen shot 2015-01-15 at 2 33 30 am](https://cloud.githubusercontent.com/assets/1707598/5751135/b4c74cf0-9c5f-11e4-9440-3961ed26e315.png)

2. The header shows "Immutable Data", which is possible a logged error?
![screen shot 2015-01-15 at 2 34 03 am](https://cloud.githubusercontent.com/assets/1707598/5751139/d297e186-9c5f-11e4-99f5-ccb4328754b3.png)

3. Random text from not in the project. I have no idea where this code is from, but I can't find it anywhere in my project. It also shows in multiple extension reference pages, so it's not just a one off thing.
![screen shot 2015-01-15 at 2 34 25 am](https://cloud.githubusercontent.com/assets/1707598/5751151/f9f7b530-9c5f-11e4-8414-055fd7fadc28.png)

**Comment by Baza207** [comment] 2015-01-15 01:48
I've also just noticed, if you use the `--skip-undocumented` flag, then only these incorrect extension classes are built and not any of the supposed correct ones.

**Comment by jpsim** [comment] 2015-01-15 02:19
Closing as duplicate of #76.

**Closed by jpsim** 2015-01-15 02:19 UTC
