### ISSUE TITLE
Methods are undocumented when conforming to a protocol.

### ISSUE THREAD

**Issue by amosavian** [realm/jazzy#842] opened 2017-07-02 16:51 UTC
Implemented methods and properties in conforming classes doesn't have inherited description from protocol one. e.g [see this one](http://cocoadocs.org/docsets/FilesProvider/0.18.0/Classes/LocalFileProvider.html#/s:FP13FilesProvider17FileProviderBasic19contentsOfDirectoryFT4pathSS17completionHandlerFTGSaCS_10FileObject_GSqPs5Error___T__T_) while the protocol [has a description](http://cocoadocs.org/docsets/FilesProvider/0.18.0/Protocols/FileProviderBasic.html#/s:FP13FilesProvider17FileProviderBasic19contentsOfDirectoryFT4pathSS17completionHandlerFTGSaCS_10FileObject_GSqPs5Error___T__T_). 

Also methods from Foundation protocols are marked as undoumented [like this one](http://cocoadocs.org/docsets/FilesProvider/0.18.0/Classes/LocalFileProvider.html#/s:FC13FilesProvider17LocalFileProvider4copyFT4withGSqV10ObjectiveC6NSZone__P_).

**Comment by SDGGiesbrecht** [comment] 2017-07-02 22:14
This is a variation of #670. Both issues request special handling of undocumented declarations wherever inheritance is involved. (The difference is that this request asks for the documentation to be automatically inherited, whereas #670 asks for it to be considered redundant and skipped.)

@amosavian, currently Jazzy does not try to understand the inheritance tree. It also does not go looking for dependency modules. Each would be no small task to implement.

If you are looking for a workaround, [one of my comments](https://github.com/realm/jazzy/issues/670#issuecomment-300906238) in the other issue may be helpful.

**Comment by johnfairh** [comment] 2017-07-17 10:45
Duplicate of #190, closing.

**Closed by johnfairh** 2017-07-17 10:45 UTC
Labels: enhancement
