### ISSUE TITLE
How do I add multiple elements in a `seealso` tag?

### ISSUE THREAD

**Issue by CCDSY** [realm/jazzy#384] opened 2015-11-17 04:53 UTC
I would like to add multiple elements in the see also tag. Something like this.
<img width="168" alt="2015-11-17 12 39 45" src="https://cloud.githubusercontent.com/assets/9509755/11202900/56a8d232-8d28-11e5-997e-96bad7c72045.png">
(I manually edited the HTML to get this layout)
But I don't know how to write the headerdoc to get it to render that way. 

I currently write it like this.
<img width="151" alt="2015-11-17 12 41 07" src="https://cloud.githubusercontent.com/assets/9509755/11202917/a48b583a-8d28-11e5-8e2b-db86e643fa23.png">
The page rendered by jazzy looks like this
<img width="693" alt="2015-11-17 12 41 01" src="https://cloud.githubusercontent.com/assets/9509755/11203083/d990d6d4-8d2a-11e5-86f3-fd96f9494951.png">

I wonder if it's a bug in jazzy. I just want to get it to look like the first image. Any suggestion on how I can do that?

**Comment by jpsim** [comment] 2015-11-24 18:19
Batched values for special Swift doc list items isn't supported at the moment. We're tracking this for parameters as well in #388.

Until that's done, I recommend you use a `- seealso:` for each item.

Closing as a duplicate of #388.

**Closed by jpsim** 2015-11-24 18:19 UTC
Labels: enhancement
