### ISSUE TITLE
Investigate generating Swift docs without compiler arguments

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#400] opened 2015-11-24 19:18 UTC
This would drastically speed up the doc generation process because we wouldn't need to build the module with `xcodebuild` prior to generating its docs.

This would also considerably simplify the gymnastics we have to do for podspecs.

We could use the information in SourceKit's `editor.open` to get us most of the way there. Almost all of the comment documentation parsing is being done within jazzy now, so really we don't rely on SourceKit's `cursorinfo` too much lately.

**Comment by orta** [comment] 2015-12-27 11:50
If you need a +1, most of the CocoaDocs issues for Swift+Jazzy I get are around the xcodebuild process

**Comment by jpsim** [comment] 2015-12-28 00:16
I'm not convinced that it's fully possible yet. It's also too early to tell if it would cause more issues than the current approach too. Not so clear cut.

**Comment by nicolas-miari** [comment] 2015-12-28 04:49
Not sure if related, but **it would really be nice to be able to generate docs for -say- just one source file** (not the whole project, every time). I checked the manual for xcodebuild and couldn't find a command to compile just one source file.

I mention this because I have a 100+ source file project, jazzy sometimes gives weird output for some of the properties and methods, and it is really time-consuming to make attempt a minor fix in the comment format and rebuild to try and track down the cause, over and over (_also, transplanting the single source file to a smaller project is not always possible because of dependencies, and trying to reproduce the same output issue in a different class, in the smaller project not always works_).

**Comment by istx25** [comment] 2016-11-23 15:24
Any progress on this since Dec 2015?

**Comment by jpsim** [comment] 2016-11-26 03:59
Not really possible given how jazzy works.

**Comment by istx25** [comment] 2016-11-26 05:44
Since it's _not possible_, I'm going to add the blocked label and close the issue. No sense keeping it open if we'll never get around to it or do it.

**Closed by istx25** 2016-11-26 05:44 UTC
Labels: blocked, enhancement
