### ISSUE TITLE
Display `throws:` for swift 2.0

### ISSUE THREAD

**Issue by cezheng** [realm/jazzy#295] opened 2015-09-10 07:39 UTC
Although I have written 

```
- throws: xxxxx
```
in my header doc, there's no way readers can see it from jazzy generated docs.

**Comment by pcantrell** [comment] 2015-09-10 13:58
This is probably #282.

**Comment by jpsim** [comment] 2015-09-10 14:49
This is indeed a duplicate of #282. This shouldn't be too much work to implement.

**Closed by jpsim** 2015-09-10 14:49 UTC
