### ISSUE TITLE
Swift version error when trying to generate ObjC docs

### ISSUE THREAD

**Issue by jessesquires** [realm/jazzy#522] opened 2016-04-12 16:34 UTC
### Steps

Generate ObjC docs for [`JSQSystemSoundPlayer`](https://github.com/jessesquires/JSQSystemSoundPlayer). With [this](https://github.com/jessesquires/JSQSystemSoundPlayer/blob/gh-pages/build_docs.sh) build script. (without specifying a `--swift-version`)

### Version
Jazzy `0.5.0`

### Error

`Unable to find an Xcode with swift version 2.1.1. (RuntimeError)`

### Fix

Specifying a Swift version fixed it: https://github.com/jessesquires/JSQSystemSoundPlayer/commit/ad2b3f913d4a10c58d1bdda3b5bbf70b90d7f4cb

The fix here was pretty easy/straight-forward, but feels really odd to specify a **Swift** version for generating **ObjC** docs. 

----------------

It looks like this was fixed by release `0.6.0`, which now defaults to Swift 2.2. However, presumably this will break when the next version of Swift is released?

### Possible solution

Should ObjC simply use the latest toolchain/runtime?

**Comment by jverkoey** [comment] 2016-04-15 14:10
I've been specifying `--swift-version $(swift --version | head -n1 | awk '{print $4}')` to get around this for now.

**Comment by jpsim** [comment] 2016-04-15 22:46
I'll close this as a duplicate of #427, since it will achieve the same result.

**Closed by jpsim** 2016-04-15 22:46 UTC
Labels: enhancement
