### ISSUE TITLE
Would it be possible to add the readme tag to custom categories as well

### ISSUE THREAD

**Issue by ad-van-erp** [realm/jazzy#565] opened 2016-05-20 15:42 UTC
I've been using the `custom_categories` section within the .jazzy.yaml for some weeks now, and I'm very enthusiastic about it. I could not derive from the documentation however, if name and children were the only allowed tags herein. I hoped there would also be a readme tag (following the conventions for this tag at top level), where I could store information about the category involved, but so far I haven't found it.

Maybe I overlooked something, otherwise I at least would be very pleased if you could add it in some future release.

**Comment by lumaxis** [comment] 2016-05-20 17:06
This is basically a duplicate of #556 ?

**Comment by jpsim** [comment] 2016-05-20 18:01
No, it's not a duplicate of #556, this is asking for more information on that feature... I'm honestly not sure, maybe @pcantrell can help you here

**Comment by ad-van-erp** [comment] 2016-05-22 07:29
It could very well be that my question was a duplicate of #556, as lumaxis suggested, and that the `abstract` option was what I needed. 
However, I'm not sure how to use it. I assumed that within the _.jazzy.yaml_ file,  `abstract` could be used as follows:

    custom_categories:

      - name: applicatietoestand
        abstract: ./docs/applicatietoestand.md
        children:
        - AdministratiefObjectId
        - ...
  
  
  but this didn't work (but jazzy didn't complain either).
  
  I now have the impression that the `abstact` option should be use at top level, that the value should be `true`, and that the behaviour looks for all the .md files within the groups, but I'm not well-versed enough in ruby to know for sure. Maybe you could help me out.

**Comment by agentk** [comment] 2016-07-13 12:38
Hi @ad-van-erp, have you made any progress with using `--abstract`?

We are using it actively on ReSwift if you want to see a reference. The files from `Docs/*.md` have some simple string replacement done on them before being copied into `Docs/tmp/api/` and running `jazzy`.

https://github.com/ReSwift/ReSwift/blob/master/.jazzy.json#L11
https://github.com/ReSwift/ReSwift/tree/master/Docs

**Comment by istx25** [comment] 2016-11-23 22:11
Closing in favour of #556. Feel free to re-open if necessary.

**Closed by istx25** 2016-11-23 22:11 UTC
Labels: duplicate, question
