### ISSUE TITLE
Missing docs with @available(iOSApplicationExtension, unavailable) and APPLICATION_EXTENSION_API_ONLY = YES

### ISSUE THREAD

**Issue by MarcoEidinger** [realm/jazzy#1376] opened 2023-12-13 18:36 UTC
```swift
@available(iOS 15.0, *)
@available(iOSApplicationExtension, unavailable)
/// API to be used in app but not in extension
public class MyApi {...}
```

in an iOS framework gets included in documentation output from Jazzy when Build Setting `APPLICATION_EXTENSION_API_ONLY = NO;`

![Jazzy Good](https://github.com/MarcoEidinger/DocUnavailableRepro/blob/main/images/jazzy_APPLICATION_EXTENSION_API_ONLY_no.png?raw=true)

The symbol gets NOT included in documentation output from Jazzy when Build Setting `APPLICATION_EXTENSION_API_ONLY = YES;`

![Jazzy Bad](https://github.com/MarcoEidinger/DocUnavailableRepro/blob/main/images/jazzy_APPLICATION_EXTENSION_API_ONLY_yes.png?raw=true)

Tested with Jazzy 0.14.4

Use https://github.com/MarcoEidinger/DocUnavailableRepro to reproduce the issue.

Expectation is that API gets documented as it can be used in an application.

**Comment by johnfairh** [comment] 2023-12-13 20:11
This looks like a Swift bug: you can look at Xcode Quick Help (I'm using 15.1b3) and see there is no quick help available for the `MyApi` but there is for `MyApi.init()` and `UniversalApi`.

Swift reports it to Jazzy as an unavailable symbol (no USR) and `"key.internal_diagnostic": "Unavailable in the current compilation context."`.  Presumably Swift is reporting it to DocC in a similarly bad way.

**Comment by johnfairh** [comment] 2023-12-15 11:15
DocC bug found its way to the Swift repo, track there.

**Comment by johnfairh** [comment] 2024-02-09 13:04
I'm going to close this because the Swift people seem to think this is working as designed on the Xcode side - at any rate doesn't seem like there is anything to do at our level.  It looks like you need to set that flag =NO when generating docs.

**Closed by johnfairh** 2024-02-09 13:04 UTC
Labels: bug, sourcekit
