### ISSUE TITLE
xcodebuild succeeds, but no documentation is generated

### ISSUE THREAD

**Issue by FelixSFD** [realm/jazzy#664] opened 2016-09-22 20:00 UTC
I'm trying to generate the documentation for a Swift-only Framework in my workspace with this command:

`jazzy --clean --xcodebuild-arguments -scheme,MyFrameworkScheme,-workspace,MyWorkspace.xcworkspace,-configuration,Release`

and with this `.jazzy.yaml`:

```
author: FelixSFD
author_url: http://www.example.com
output: ../docs/Framework
min_acl: private
```

Xcodebuild is running without errors and all files are parsed. But when the process is done, the Documentation folder is empty. There is only the `undocumented.json` file.
Additionally, I'm getting this warning:

> `DEBUG` has no USR. First make sure all modules used in your project have been imported. If all used modules are imported, please report this problem by filing an issue at https://github.com/realm/jazzy/issues along with your Xcode project. If this token is declared in an `#if` block, please ignore this message.

Is this a bug or what am I doing wrong?

**Comment by istx25** [comment] 2016-11-23 23:27
Hi @FelixSFD. Thanks for reaching out. My apologies that no one has responded to your support request until now. I will have to do some more research to understand the problem better. Please feel free to close the issue if help is no longer needed or necessary.

**Comment by FelixSFD** [comment] 2016-11-24 11:34
The issue still persists. Please let me know, if you need more information.

**Comment by istx25** [comment] 2016-11-24 11:58
Thank you for clarifying.

**Comment by istx25** [comment] 2016-12-12 19:14
Closing as a duplicate of #657.

**Closed by istx25** 2016-12-12 19:14 UTC
Labels: duplicate
