### ISSUE TITLE
Parameter documentation is not stripped from the description.

### ISSUE THREAD

**Issue by andersio** [realm/jazzy#718] opened 2016-12-26 05:05 UTC
[It seems Jazzy somehow let parameter docs in this specific format slip through](http://reactivecocoa.io/reactiveswift/docs/latest/Protocols/SignalProtocol.html#/s:Fe13ReactiveSwiftRxS_14SignalProtocolwx5ErrorzO6Result7NoErrorrS0_13observeValuesFFwx5ValueT_GSqPS_10Disposable__):

```swift
- parameters:
  - count: The count.
  - thing: Something.
```

That's said the parameter docs were parsed correctly. Just that it wasn't stripped from the description afterwards.

**Comment by SDGGiesbrecht** [comment] 2016-12-26 19:07
This has been fixed. (It is a duplicate of #431 and #673). It is just waiting for the next release. If you want to use the fixed version now, see [here](https://github.com/realm/jazzy/issues/637#issuecomment-267476495) for instructions on building from source.

**Closed by SDGGiesbrecht** 2016-12-26 19:07 UTC
Labels: duplicate

**Comment by andersio** [comment] 2016-12-26 20:25
Glad to know. Thanks. 😸
