### ISSUE TITLE
NSCalendar extension Undocumented

### ISSUE THREAD

**Issue by valery-bashkatov** [realm/jazzy#579] opened 2016-06-09 19:06 UTC
I have extension for the NSCalendar, but Jazzy doesn't document its description.
Jazzy 0.6.2

Example:
`import Foundation

/// `NSCalendar` extension for testing Jazzy
public extension NSCalendar {
    public var test: Double {
        return 1
    }
}`

And the documentation looks like this:
<img width="744" alt="screen shot 2016-06-09 at 22 03 27" src="https://cloud.githubusercontent.com/assets/18283239/15942675/73c054a2-2e96-11e6-916b-d47638ad7d7f.png">

**Comment by jpsim** [comment] 2016-06-09 20:09
Looks like a duplicate of #454. I have a fix for that in the works.

**Closed by jpsim** 2016-06-09 20:09 UTC
