### ISSUE TITLE
Declaration of constrained extension not helpful

### ISSUE THREAD

**Issue by reitzig** [realm/jazzy#881] opened 2017-09-20 12:48 UTC
I have an extension like this:

```swift
public extension Set where Element == MyType {
	...
}
```

Jazzy prints as declaration:

	struct Set<Element> : SetAlgebra, Hashable, Collection, ExpressibleByArrayLiteral where Element : Hashable

This just seems to be the original declaration of `Set`, which gives exactly zero information about the scope of the extension.

**Comment by SDGGiesbrecht** [comment] 2017-09-20 18:22
@reitzig,

Extensions are included under the parent type by design.

Unfortunately, constraints are not listed automatically yet.

However, in the meantime, a simple workaround exists using `// MARK: -`. Compare [this source](https://github.com/SDGGiesbrecht/SDGCornerstone/blob/e600ec587b4513d4ee9a5f1bbd2071219d0615af/Sources/SDGCornerstone/Localization/UserFacingText.swift#L48) with [this documentation](https://sdggiesbrecht.github.io/SDGCornerstone/macOS/Structs/UserFacingText.html). I tend to be forgetful when it comes to this, so I built validation for it into [Workspace](https://github.com/SDGGiesbrecht/Workspace#workspace)’s proofreading phase. It throws warnings for any constrained extensions that are missing `// MARK: -`.

**Comment by reitzig** [comment] 2017-09-21 07:55
Side note: what I *really* want is

```swift
typealias MySet = Set<MyType>

extension Myset { ... }
```

And then have an entry `MySet` in the Jazzy doc. Unfortunately, the above is not valid Swift code, so I'm out of luck.

Imho, constrained extensions should be listed separately. Stuff declared in `extension Set where Element == Int` and `extension Set where Element == String` are *never* available on the same object, so it doesn't make a whole lot of sense to list them together.

**Comment by johnfairh** [comment] 2017-09-21 11:17
Closing this one, duplicate of #717.

**Closed by johnfairh** 2017-09-21 11:17 UTC
