### ISSUE TITLE
Document inherited declarations (whether via subclasses or default protocol implementations)

### ISSUE THREAD

**Issue by yeelan0319** [realm/jazzy#545] opened 2016-04-28 14:56 UTC
Hi Jazzy team,

I want to ask for a feature that can generate document page for those classes that don't have their own method but purely inherit from their parent class.

For example, bar.h
```
#import "foo.h"

/**
This is a class that has a different implementation than their parent.
*/
@interface bar : foo
@end
```

Currently, Jazzy only provides an expandable box on the classes.html for classes like this and "docs/Classes/bar.html" doesn't exist. It is also true empty protocols. However, it is inconsistent from the other pages and seems broken for our documentation site. 

I heard this feature used to be available in Doxygen and we have several classes/protocols like this, so we hope that Jazzy may consider also to generate a separate page for them.

Thanks!

**Comment by jpsim** [comment] 2016-07-20 19:13
Closing as a duplicate of #190.

**Closed by jpsim** 2016-07-20 19:13 UTC
Labels: d3:hard, feature, p3, ruby
