### ISSUE TITLE
Comments after Function name showing up

### ISSUE THREAD

**Issue by khoogheem** [realm/jazzy#156] opened 2015-01-16 15:35 UTC
Here is what is generated by jazzy:
~~~
public class func addSkipBackupAttributeToItemsAtPath(filePath: String) -> Bool {
		//Che
~~~
 
This is the code:

~~~
	public class func addSkipBackupAttributeToItemsAtPath(filePath: String) -> Bool {
		//Check if the file/path is even valid
		if !NSFileManager.defaultManager().fileExistsAtPath(filePath) {
			return false
		}
~~~

I would expect that any comments after the { should not be showing up...

**Comment by emaloney** [comment] 2015-01-16 17:05
This looks related to an issue I found here: https://github.com/realm/jazzy/issues/145

**Comment by jpsim** [comment] 2015-01-16 18:21
@emaloney is right that this is a duplicate of #145.

**Closed by jpsim** 2015-01-16 18:21 UTC
