### ISSUE TITLE
Swift code formatting does not work properly for some callouts

### ISSUE THREAD

**Issue by blochberger** [realm/jazzy#629] opened 2016-08-01 18:39 UTC
I tried to document postconditions with the `postcondition` callout, providing example Swift code for assertions for the documented postconditions:

`````` swift
/**
    Does something.

    - Postcondition:
      Never returns `false`.
      ```swift
      let result = doSomething()
      assert(result)
      ```
*/
func doSomething() -> Bool {
    …
}
``````

This works fine in Xcode, but renders incorrectly with `jazzy`:

> Does something.
> 
> > POSTCONDITION
> > Never returns `false`. `swift let result = doSomething() assert(result)`

If I add another new line before the code example, like:

`````` swift
/**
    Does something.

    - Postcondition:
      Never returns `false`.

      ```swift
      let result = doSomething()
      assert(result)
      ```
*/
public func doSomething() -> Bool {
    …
}
``````

The output looks like:

> Does something.
> 
> > POSTCONDITION
> > Never returns false.
> 
> ``` swift
> let result = doSomething()
> assert(result)
> ```

Note that the output is no longer in the block describing the postcondition.

**Comment by jpsim** [comment] 2016-11-26 00:21
The issue here isn't related to `Postcondition`, as that keyword is supported. See https://github.com/realm/jazzy/blob/v0.7.2/lib/jazzy/jazzy_markdown.rb#L22-L45

I think the problem is related to how [redcarpet](https://github.com/vmg/redcarpet) parses the Markdown in this case.

Maybe it doesn't consider the entire block to actually be a valid single list entry? Would be worth trying to parse just that with redcarpet and see how it handles it.

**Comment by istx25** [comment] 2016-11-26 01:42
Just assigned this ticket to you. I'll let you take over here. 💃

**Comment by SDGGiesbrecht** [comment] 2016-12-15 23:54
@blochberger, you are using non‐standard Markdown. Specifying a language like ` ```swift ` is a [GitHub extension](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown).

As far as Xcode rendering it properly anyway, I think you are just lucky.

Try it without the `swift` marker and see what happens. Syntax coloring is automatic in both Xcode and Jazzy anyway.

**Comment by jpsim** [comment] 2016-12-16 20:30
Actually @SDGGiesbrecht that _shouldn't_ be it, since we use recarpet with `fenced_code_blocks: true`: https://github.com/realm/jazzy/blob/v0.7.3/lib/jazzy/jazzy_markdown.rb#L89

And according to their readme: https://github.com/vmg/redcarpet#and-its-like-really-simple-to-use

> * `:fenced_code_blocks`: parse fenced code blocks, PHP-Markdown
> style. Blocks delimited with 3 or more `~` or backticks will be considered
> as code, without the need to be indented. An optional language name may
> be added at the end of the opening fence for the code block.

**Comment by SDGGiesbrecht** [comment] 2016-12-17 00:03
I went back and tried it myself. 

You are right. My suggestion only stops “swift” from creeping in. It does not solve the line breaking.
```html
<div class="aside aside-postcondition">
    <p class="aside-title">Postcondition</p>
    <p>Never returns <code>false</code>.
<code>
let result = doSomething()
assert(result)
		</code></p>

</div>
```
is better than:
```html
<div class="aside aside-postcondition">
    <p class="aside-title">Postcondition</p>
    <p>Never returns <code>false</code>.
<code>swift
let result = doSomething()
assert(result)
</code></p>

</div>
```
but still doesn’t match behaviour elsewhere:
```html
<pre class="highlight swift"><code><span class="k">let</span> <span class="nv">result</span> <span class="o">=</span> <span class="nf">doSomething</span><span class="p">()</span>
<span class="nf">assert</span><span class="p">(</span><span class="n">result</span><span class="p">)</span>
</code></pre>
```

I was wrong about two syntax colouring too. Syntax coloring doesn’t exist in Quick Help. And for Jazzy, specifying the language *is* required.

**Comment by SDGGiesbrecht** [comment] 2016-12-17 00:53
I think the following means either recarpet has a bug, or at least recarpet cannot be used to parse callouts as if they were lists.

⁂

I tracked it to [`sourcekitten.rb`, line 262](https://github.com/realm/jazzy/blob/master/lib/jazzy/sourcekitten.rb#L262).

Printing before and after...
```ruby
p doc['key.doc.comment'] || ''
declaration.abstract = Jazzy.markdown.render(doc['key.doc.comment'] || '')
p declaration.abstract
```
...shows the problem happens there...
```html
"Does something.\n\n- Postcondition:\nNever returns `false`.\n```swift\nlet result = doSomething()\nassert(result)\n```"
"<p>Does something.</p>\n<div class=\"aside aside-postcondition\">\n    <p class=\"aside-title\">Postcondition</p>\n    Never returns <code>false</code>.\n<code>swift\nlet result = doSomething()\nassert(result)\n</code>\n\n</div>\n"
```

Printing the parameters of [`jazzy_markdown.rb`, line 262](https://github.com/realm/jazzy/blob/master/lib/jazzy/jazzy_markdown.rb#L67)...
```ruby
def list_item(text, _list_type)
  p text
```
...shows the HTML is already faulty when recarpet passes it to us...
```html
"Postcondition:\nNever returns <code>false</code>.\n<code>swift\nlet result = doSomething()\nassert(result)\n</code>\n"
```

∴ The faulty processing happens while the source is in recarpet’s control.

**Comment by johnfairh** [comment] 2017-04-26 10:55
This works fine for lists / most callouts provided you work out / guess the whitespace correctly.

For multiple paragraphs in listitems, including callouts like `postcondition`, redcarpet requires that you use a 4-space indent *from the bullet that began the list item*.  So the following works in both Xcode and jazzy without any code changes anywhere:

    /// - Postcondition:
    ///   Never returns `false`.
    ///
    ///     ```swift
    ///     let result = doSomething()
    ///     assert(result)
    ///     ```

Making this work for params + returns is a bit more complex, which is what 476 is about.

The only thing that this issue could fix is the inconsistent indentation requirements between jazzy + Xcode, but that gets into the 'change markdown engine' space.

**Comment by jpsim** [comment] 2017-05-01 22:50
Fixed in #795.

**Closed by jpsim** 2017-05-01 22:50 UTC
Labels: bug, difficulty-hard, front-end

**Comment by blochberger** [comment] 2017-08-10 15:10
This might be a regression: Now it renders as:

> Does something.
> 
> > POSTCONDITION
>> postcondition:
> > Never returns false.
> >
> > ``` swift
> > let result = doSomething()
> > assert(result)
> > ```

See the superfluous "postcondition:" there?

**Comment by johnfairh** [comment] 2017-08-10 15:41
Can you post the exact comment you are using?  This works for me (0.8.3):

```
/**
    Does something.
    - Postcondition:
      Never returns `false`.

        ```
        let result = doSomething()
        assert(result)
        ```
*/
func doSomething() -> Bool {
    return true
}
```
![screen shot 2017-08-10 at 16 35 34](https://user-images.githubusercontent.com/26768470/29178604-f7b78804-7de9-11e7-827c-3724808e1b48.png)

**Comment by blochberger** [comment] 2017-08-10 15:52
I can reproduce it with the following code:

```swift
/**
    Does something.
    - Postcondition:

        ```
        let result = doSomething()
        assert(result)
        ```
*/
func doSomething() -> Bool {
	return true
}
```

If I add a line of text before the ``` the "Postcondition:" will not occur. If I remove the empty line the rendered code will contain no line breaks.

**Comment by johnfairh** [comment] 2017-08-10 16:18
Thanks - yep I see.  There is a jazzy bug here: there needs to be at least a space after the colon.  (If your Xcode is like set up like mine though that is tough to maintain...)
