### ISSUE TITLE
Failing but the reason is not clear. 

### ISSUE THREAD

**Issue by rodriguise** [realm/jazzy#161] opened 2015-02-09 17:03 UTC
Failed to generate documentation
```
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/lib/jazzy/sourcekitten.rb:51:in `run_sourcekitten': Running `/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/lib/jazzy/sourcekitten/sourcekitten doc` failed:  (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'
```

**Comment by segiddins** [comment] 2015-02-09 17:07
This is a known issue with sourcekitten.

**Comment by Simulacrotron** [comment] 2015-02-18 22:28
@segiddins is there any workaround

**Comment by Bierrot** [comment] 2015-03-05 13:33
Same here, only for objective-c project

**Comment by segiddins** [comment] 2015-04-02 22:37
This should be fixed in Jazzy 0.1.2?

**Comment by jpsim** [comment] 2015-04-03 17:53
I'm unsure what this issue is, so I can't say if it will be fixed in the next version of jazzy. If you can run sourcekitten on your project and post the output here, I'll be able to help troubleshoot.

**Comment by jpsim** [comment] 2015-04-30 23:00
@rodriguise @Simulacrotron @Bierrot could you check to see if this issue still happens with the latest version of jazzy (0.2.0)? If it does, please share steps to reproduce. Thanks!

**Comment by nicolas-miari** [comment] 2015-09-02 05:52
I get a similar error log (Xcode 7 Beta 5, Swift 2):

    fatal error: unexpectedly found nil while unwrapping an Optional value
	    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.4/lib/jazzy/sourcekitten.rb:71:in `run_sourcekitten'
	    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.4/lib/jazzy/doc_builder.rb:53:in `block in build'
	    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.4/lib/jazzy/doc_builder.rb:51:in `chdir'
	    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.4/lib/jazzy/doc_builder.rb:51:in `build'
	    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.4/bin/jazzy:15:in `<top (required)>'
	    from /usr/bin/jazzy:23:in `load'
	    from /usr/bin/jazzy:23:in `<main>'

...is it the same issue?

**Comment by jpsim** [comment] 2015-09-02 06:33
@nicolas-miari the version of jazzy you're using only targets Swift 1.2. For Swift 2.0 support (only with Xcode 7 Beta 6), please use the `swift-2.0` branch (#261).

**Comment by nicolas-miari** [comment] 2015-09-02 06:39
Great, thanks! Sorry I missed that.

**Comment by nicolas-miari** [comment] 2015-09-02 08:10
I had some issues building `json -v 1.8.3` during the `bundle install` part, but after installing the xcode command line tools (as suggested somewhere), it worked! All my project's classes and extensions are documented (`--min-acl internal`)

Because of the wording of Jazzy's README.md page, I was afraid I also would have to build sourcekitten from source, but that doesn't seem to be the case.

**Comment by nicolas-miari** [comment] 2015-09-02 08:23
...aaaand, the same command fails when I paste it to Xcode's RunScript phase (so that my docs update everytime I build the target):


    /Users/(my_username)/Projects/Jazzy/jazzy.gemspec:17: warning: Insecure world writable dir /usr in PATH, mode 040777
    /Users/(my_username)/Projects/Jazzy/lib/jazzy/sourcekitten.rb:72:in `run_sourcekitten': undefined method     `as_env' for nil:NilClass (NoMethodError)
    	    from /Users/(my_username)/Projects/Jazzy/lib/jazzy/doc_builder.rb:53:in `block in build'
	    from /Users/(my_username)/Projects/Jazzy/lib/jazzy/doc_builder.rb:51:in `chdir'
	    from /Users/(my_username)/Projects/Jazzy/lib/jazzy/doc_builder.rb:51:in `build'
	    from /Users/(my_username)/Projects/Jazzy/bin/jazzy:15:in `<main>'
    Command /bin/sh failed with exit code 1

_(side note: yes, I built the gem into `~/Projects/Jazzy/bin/` and haven't played with the `PATH` yet... Not sure what's the best course of action; but for now I run jazzy with the full path to the executable)_

Any tips on what could be happening?

**Comment by jpsim** [comment] 2015-09-02 16:00
@nicolas-miari in your case, jazzy is failing because it can't find an Xcode version for the version of Swift you've requested (or 1.2 by default). Could you please open a new issue so we can troubleshoot?

**Comment by nicolas-miari** [comment] 2015-09-03 01:20
Weird... I did run xcode-select to point to the (laterst) beta. Will open issue now, thanks!

**Closed** 2015-11-24 00:28 UTC
Labels: bug
