### ISSUE TITLE
Error when building site 

### ISSUE THREAD

**Issue by damianesteban** [realm/jazzy#889] opened 2017-10-01 20:26 UTC
I'm executing the following command:

```
bundle exec jazzy --clean --author me --author_url https://www.me.com --github_url https://github.com/me/me --github_file_prefix https://github.com/me/me/releases/tag/release-2.0.1b8 --xcodebuild-arguments -scheme,Development --module Me --output docs/output
```

In case you couldn't tell, the "me"s are placeholders 😄 

Here is the error message:

```
building site
bundler: failed to load command: jazzy (/Users/damianesteban/.rbenv/versions/2.4.2/bin/jazzy)
JSON::ParserError: 416: unexpected token at ',

  /Users/damianesteban/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
  /Users/damianesteban/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
  /Users/damianesteban/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/jazzy-0.0.14/lib/jazzy/sourcekitten.rb:162:in `parse'
  /Users/damianesteban/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/jazzy-0.0.14/lib/jazzy/doc_builder.rb:94:in `build_docs_for_sourcekitten_output'
  /Users/damianesteban/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/jazzy-0.0.14/lib/jazzy/doc_builder.rb:51:in `build'
  /Users/damianesteban/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/jazzy-0.0.14/bin/jazzy:15:in `<top (required)>'
  /Users/damianesteban/.rbenv/versions/2.4.2/bin/jazzy:23:in `load'
  /Users/damianesteban/.rbenv/versions/2.4.2/bin/jazzy:23:in `<top (required)>'

```

I recall having a similar issue with jazzy before but I'm unable to resolve this one.

**Comment by jpsim** [comment] 2017-10-01 23:10
Have you tried quoting the comma-separated list?

```
bundle exec jazzy --clean --author me --author_url https://www.me.com --github_url https://github.com/me/me --github_file_prefix https://github.com/me/me/releases/tag/release-2.0.1b8 --xcodebuild-arguments "-scheme,Development" --module Me --output docs/output
```

**Comment by damianesteban** [comment] 2017-10-02 00:24
I just did and unfortunately I'm getting the same error.

**Comment by damianesteban** [comment] 2017-10-02 02:16
When I just run:

`$ jazzy`

without any other options I get a similar error, but here is the output:

```
	from /Users/damianesteban/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
	from /Users/damianesteban/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/jazzy-0.0.14/lib/jazzy/sourcekitten.rb:162:in `parse'
	from /Users/damianesteban/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/jazzy-0.0.14/lib/jazzy/doc_builder.rb:94:in `build_docs_for_sourcekitten_output'
	from /Users/damianesteban/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/jazzy-0.0.14/lib/jazzy/doc_builder.rb:51:in `build'
	from /Users/damianesteban/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/jazzy-0.0.14/bin/jazzy:15:in `<top (required)>'
	from /Users/damianesteban/.rbenv/versions/2.4.2/bin/jazzy:23:in `load'
	from /Users/damianesteban/.rbenv/versions/2.4.2/bin/jazzy:23:in `<main>'
```

**Comment by johnfairh** [comment] 2017-10-02 14:24
> 	from /Users/..../gems/jazzy-0.0.14/...

It would be worth updating to latest jazzy 0.8.4 and trying again: even if it still fails, will be easier to debug on newer code.

**Comment by cyupa** [comment] 2017-11-01 09:50
I have the same issue, still investigating.

**Comment by jjochen** [comment] 2017-12-15 14:00
same here

**Comment by johnfairh** [comment] 2017-12-19 12:39
@jjochen happy to help if you can provide a recreate example.  @cyupa, @damianesteban did you solve your problems?  Can you share how?

**Comment by jjochen** [comment] 2017-12-19 20:23
I found my mistake: 

My `Gemfile` looked like that
```
source 'https://rubygems.org' do
  gem 'xcpretty'
  gem 'jazzy'
  ...
end
```
Which results in `jazzy` version `0.0.14`.
The latest version of `xcpretty` depends on rouge `(~> 2.0.7)`.
The latest version of `jazzy` depends on rouge `(~> 1.5)`.

Specifying the version of `jazzy` solved my issue:
```
source 'https://rubygems.org' do
  gem 'xcpretty'
  gem 'jazzy', '>= 0.9.0'
  ...
end
```

It's a pity that you can't use the latest version of `xcpretty`, though.

**Comment by jpsim** [comment] 2017-12-19 20:44
> It's a pity that you can't use the latest version of xcpretty, though.

I think by xcpretty, you mean rouge, and feel free to make a PR to update it.

**Comment by johnfairh** [comment] 2017-12-19 20:45
Thanks for getting back - I have a rouge 3.0 branch almost ready to go, not sure if that will help or create a different dependency problem.

**Comment by jpsim** [comment] 2017-12-19 20:46
Awesome!

**Comment by johnfairh** [comment] 2017-12-21 12:42
Jazzy master now requires rouge >= 2.0.6, < 4.  Closing this issue - guessing that was the cause of at least OP also ending up with jazzy 0.0.14 --- rouge was added as a dependency in 0.0.15!

**Closed by johnfairh** 2017-12-21 12:42 UTC
Labels: help
