### ISSUE TITLE
Adds `class="para"` to all README <p> tags

### ISSUE THREAD

**Issue by p2** [realm/jazzy#195] opened 2015-03-25 20:26 UTC
Took me a while to figure out why everything on the index page was so huge, except list items. It looks like v 0.1.4 wraps all README paragraphs in `<p class="para">`. Removing these classes manually after build makes everything look as it should.

**Comment by segiddins** [comment] 2015-03-25 21:09
Closing as a duplicate of #95.

**Closed by segiddins** 2015-03-25 21:09 UTC
