### ISSUE TITLE
Code not using Menlo font outside of README

### ISSUE THREAD

**Issue by beltex** [realm/jazzy#137] opened 2015-01-02 20:06 UTC
Code inside a README displays fine, uses Menlo at 12px (like Apple's own docs), but anywhere else it's monospace at 11px (which is quite illegible in comparison). Looks like `jazzy.css.scss` doesn't apply the [style](https://github.com/realm/jazzy/blob/master/lib/jazzy/assets/css/jazzy.css.scss#L666-668) to `code` elsewhere.

**Comment by segiddins** [comment] 2015-01-02 20:32
We'd love to see a PR changing that! (With screenshots for comparison, to make seeing the before/after difference easier)

**Comment by jpsim** [comment] 2015-01-02 21:39
I'm closing this as a duplicate of #95, which would fix this and more.

**Closed by jpsim** 2015-01-02 21:39 UTC

**Comment by beltex** [comment] 2015-01-04 03:39
@segiddins Sure! :)

@jpsim Not a problem. Would you be open to taking a small patch for this in the meantime, since this is user facing?

### Patch

```diff
diff --git a/lib/jazzy/assets/css/jazzy.css.scss b/lib/jazzy/assets/css/jazzy.css.scss
index f4b14b4..e1c22b0 100644
--- a/lib/jazzy/assets/css/jazzy.css.scss
+++ b/lib/jazzy/assets/css/jazzy.css.scss
@@ -1,5 +1,6 @@
 $doc_coverage_color: #999;
 $content_wrapper_width: 980px;
+$code-font: 12px Menlo, monospace;

 html, body, div, span, h1, h3, h4, p, a, code, em, img, ul, li, table, tbody, tr, td {
   background: transparent;
@@ -97,6 +98,7 @@ html, body, div, span, h1, h3, h4, p, a, code, em, img, ul, li, table, tbody, tr
     font-size: 1.4em;
     word-break: break-all;
     > code {
+      font: $code-font;
       display: inline-block;
     }
   }
@@ -149,6 +151,7 @@ html, body, div, span, h1, h3, h4, p, a, code, em, img, ul, li, table, tbody, tr
   .section .declaration {
     margin-top: 21px;
     code {
+      font: $code-font;
       color: rgba(128, 128, 128, 1);
       margin-bottom: 15px;
       padding-bottom: 6px;
```

### Before

![screen shot 2015-01-03 at 10 33 33 pm](https://cloud.githubusercontent.com/assets/2666961/5604650/efaaea36-9398-11e4-8c44-58c8044625e3.png)

### After

Tested on Firefox & Safari.

![screen shot 2015-01-03 at 10 32 42 pm](https://cloud.githubusercontent.com/assets/2666961/5604651/fb2c558e-9398-11e4-842d-bd70e2afe1c7.png)

**Comment by beltex** [comment] 2015-02-26 19:46
Ping! :)

Only because #95 could take a while till its implemented.

**Comment by segiddins** [comment] 2015-02-26 19:47
Sure, send in a PR and I'd be happy to take a look!

**Comment by beltex** [comment] 2015-02-26 22:58
Awesome! :)
